package net.metadata.openannotation.lorestore.servlet;

public abstract class OATestRecords {
    private OATestRecords() {}
    /* Sample annos for validation tests : all in TriG format */

    public static final String OA_BASIC = "@prefix oa: <http://www.w3.org/ns/oa#> ."
            + "<http://localhost:8080/lorestore/oa/sopabasic> {"
            + "<http://localhost:8080/lorestore/oa/sopabasic> a oa:Annotation ; "
            + "oa:hasBody <http://www.youtube.com/watch?v=uPh81LIe7B8> ; " 
            + "oa:hasTarget <http://en.wikipedia.org/> .}";
    public static final String OA_BASIC_MULTIPLE = "@prefix oa: <http://www.w3.org/ns/oa#> ."
            + "<http://localhost:8080/lorestore/oa/sopabasic> {"
            + "<http://localhost:8080/lorestore/oa/sopabasic> a oa:Annotation ; "
            + "oa:hasBody <http://www.youtube.com/watch?v=uPh81LIe7B8> ; " 
            + "oa:hasTarget <http://en.wikipedia.org/> .}"
            + "<http://localhost:8080/lorestore/oa/sopabasic2> {"
            + "<http://localhost:8080/lorestore/oa/sopabasic2> a oa:Annotation ; "
            + "oa:hasBody <http://www.youtube.com/watch?v=uPh81LIe7B8> ; " 
            + "oa:hasTarget <http://en.wikipedia.org/> .}";
    
    // completely contrived annotation example that covers all aspects of the validation rules
    public static final String OA_ALL_RULES_PASS = "@prefix oa: <http://www.w3.org/ns/oa#> . "
            + "@prefix foaf: <http://xmlns.com/foaf/0.1/> . "
            + "@prefix dctypes: <http://purl.org/dc/dcmitype/> . "
            + "@prefix cnt: <http://www.w3.org/2011/content#> . "
            + "@prefix dc: <http://purl.org/dc/elements/1.1/> . "
            + "@prefix prov: <http://www.w3.org/ns/prov#> . "
            + "@prefix ex: <http://example.org/> . "
            + "@prefix skos: <http://www.w3.org/2004/02/skos/core#> . "
            + "@prefix dcterms: <http://purl.org/dc/terms/> . "
            + "@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> . "
            + "<http://localhost:8080/lorestore/oa/sopabasic> {"
            + "<http://localhost:8080/lorestore/oa/sopabasic> a oa:Annotation ; "
            + "oa:hasBody <urn:uuid:b42b3210-9686-11e2-9e96-0800200c9a66>  ; "
            + "oa:hasBody ex:MyTag; "
            + "oa:annotatedBy <http://example.org/user1> ; "
            + "oa:serializedBy <http://example.org/software1> ; "
            + "oa:annotatedAt \"2012-02-12T15:02:14Z\" ; "
            + "oa:motivatedBy ex:specialisedMotivation, oa:tagging ; " 
            + "oa:hasTarget <urn:uuid:89ef7820-9687-11e2-9e96-0800200c9a66> . "
            + "<urn:uuid:89ef7820-9687-11e2-9e96-0800200c9a66> a oa:SpecificResource ; "
            + "oa:hasSelector <urn:uuid:b6a4aa90-9757-11e2-9e96-0800200c9a66> ; "
            + "oa:hasState <urn:uuid:746a6730-9759-11e2-9e96-0800200c9a66> ; " 
            + "oa:hasSource <http://www.example.org/mypage.html> . "
            + "<urn:uuid:b6a4aa90-9757-11e2-9e96-0800200c9a66> a oa:Choice ; "
            + "oa:item <urn:uuid:0bf18730-96a3-11e2-9e96-0800200c9a66> ; "
            + "oa:item <urn:uuid:a1b44420-975b-11e2-9e96-0800200c9a66> ; "
            + "oa:item <urn:uuid:96fe18c0-9757-11e2-9e96-0800200c9a66> ; "
            + "oa:item <urn:uuid:a94e8db0-9758-11e2-9e96-0800200c9a66> ; "
            + "oa:default <urn:uuid:0bf18730-96a3-11e2-9e96-0800200c9a66> . "
            + "<urn:uuid:746a6730-9759-11e2-9e96-0800200c9a66> a oa:Composite ; "
            + "oa:item <urn:uuid:a30a2ca0-975a-11e2-9e96-0800200c9a66> ; "
            + "oa:item <urn:uuid:7645af80-975c-11e2-9e96-0800200c9a66> . "
            + "<urn:uuid:0bf18730-96a3-11e2-9e96-0800200c9a66> a oa:FragmentSelector ; " 
            + "dcterms:conformsTo <http://tools.ietf.org/rfc/rfc3236> ; "
            + "rdf:value \"#foo\" . "
            + "<urn:uuid:96fe18c0-9757-11e2-9e96-0800200c9a66> a oa:TextPositionSelector ; " 
            + "oa:start \"10\" ; "
            + "oa:end \"20\" . "
            + "<urn:uuid:a1b44420-975b-11e2-9e96-0800200c9a66> a oa:DataPositionSelector ; " 
            + "oa:start \"10\" ; "
            + "oa:end \"20\" . "
            + "<urn:uuid:a94e8db0-9758-11e2-9e96-0800200c9a66> a oa:TextQuoteSelector ; " 
            + "oa:exact \"bar\" ; "
            + "oa:suffix \" baz\" ; "
            + "oa:prefix \"foo \" . "
            + "<urn:uuid:7645af80-975c-11e2-9e96-0800200c9a66> a oa:HTTPRequestState ; "
            + "rdf:value \"foo\" . "
            + "<urn:uuid:a30a2ca0-975a-11e2-9e96-0800200c9a66> a oa:TimeState ; " 
            + "oa:when \"2012-02-12T15:02:14Z\" . "
            + "<http://example.org/user1> a foaf:Person ; " 
            + "foaf:name \"Joe Bloggs\" . "
            + "<http://example.org/software1> a prov:SoftwareAgent ; "
            + "foaf:name \"Demo software\" . "
            + "<urn:uuid:d609bd10-9687-11e2-9e96-0800200c9a66> a cnt:ContentAsBase64, dctypes:Text ; "
            + "cnt:bytes \"content\" ; "
            + "cnt:characterEncoding \"UTF-8\" ; "
            + "dc:format \"text/plain\" . "
            + "<urn:uuid:b42b3210-9686-11e2-9e96-0800200c9a66> a cnt:ContentAsText, dctypes:Text ; "
            + "cnt:chars \"content\" ; "
            + "dc:language \"en-US\" ; "
            + "cnt:characterEncoding \"UTF-8\" ; "
            + "dc:format \"text/plain\" . "
            + "<http://www.example.org/mypage.html> a dctypes:Text . "
            + "ex:specialisedMotivation a oa:Motivation ; "
            + "skos:broader oa:commenting . "
            + "ex:MyTag a oa:SemanticTag. "
            + "}";    

    public static final String OA_BASIC_FULLY_VALID = "@prefix oa: <http://www.w3.org/ns/oa#> . " 
            + "@prefix foaf: <http://xmlns.com/foaf/0.1/> . "
            + "@prefix dctypes: <http://purl.org/dc/dcmitype/> . "
            + "<http://localhost:8080/lorestore/oa/sopabasic> { "
            + "<http://localhost:8080/lorestore/oa/sopabasic> a oa:Annotation ; "
            + "oa:annotatedBy <http://example.org/user1> ; "
            + "oa:annotatedAt \"2012-02-12T15:02:14Z\" ; "
            + "oa:motivatedBy oa:commenting ; "
            + "oa:hasBody <http://www.youtube.com/watch?v=uPh81LIe7B8> ; "
            + "oa:hasTarget <http://en.wikipedia.org/> ."
            + "<http://example.org/user1> a foaf:Person ; "
            + "foaf:name \"Joe Bloggs\" . "
            + "<http://www.youtube.com/watch?v=uPh81LIe7B8> a dctypes:MovingImage ."
            + "<http://en.wikipedia.org/> a dctypes:Text . "
            + "}";
    public static final String OA_SERIALIZEDBY = "@prefix oa: <http://www.w3.org/ns/oa#> . " 
            + "@prefix foaf: <http://xmlns.com/foaf/0.1/> . "
            + "@prefix dctypes: <http://purl.org/dc/dcmitype/> . "
            + "@prefix prov: <http://www.w3.org/ns/prov#> . "
            + "<http://localhost:8080/lorestore/oa/sopabasic> { "
            + "<http://localhost:8080/lorestore/oa/sopabasic> a oa:Annotation ; "
            + "oa:annotatedBy <http://example.org/user1> ; "
            + "oa:serializedBy <http://example.org/software1> ; "
            + "oa:annotatedAt \"2012-02-12T15:02:14Z\" ; "
            + "oa:motivatedBy oa:commenting ; "
            + "oa:hasBody <http://www.youtube.com/watch?v=uPh81LIe7B8> ; "
            + "oa:hasTarget <http://en.wikipedia.org/> ."
            + "<http://example.org/user1> a foaf:Person ; "
            + "foaf:name \"Joe Bloggs\" . "
            + "<http://www.youtube.com/watch?v=uPh81LIe7B8> a dctypes:MovingImage ."
            + "<http://en.wikipedia.org/> a dctypes:Text . "
            + "<http://example.org/software1> a prov:SoftwareAgent ; "
            + "foaf:name \"Demo software\" ."
            + "}";
    public static final String OA_NO_SOFTWAREAGENT = "@prefix oa: <http://www.w3.org/ns/oa#> . " 
            + "@prefix foaf: <http://xmlns.com/foaf/0.1/> . "
            + "@prefix dctypes: <http://purl.org/dc/dcmitype/> . "
            + "<http://localhost:8080/lorestore/oa/sopabasic> { "
            + "<http://localhost:8080/lorestore/oa/sopabasic> a oa:Annotation ; "
            + "oa:annotatedBy <http://example.org/user1> ; "
            + "oa:serializedBy <http://example.org/software1> ; "
            + "oa:annotatedAt \"2012-02-12T15:02:14Z\" ; "
            + "oa:motivatedBy oa:commenting ; "
            + "oa:hasBody <http://www.youtube.com/watch?v=uPh81LIe7B8> ; "
            + "oa:hasTarget <http://en.wikipedia.org/> ."
            + "<http://example.org/user1> a foaf:Person ; "
            + "foaf:name \"Joe Bloggs\" . "
            + "<http://www.youtube.com/watch?v=uPh81LIe7B8> a dctypes:MovingImage ."
            + "<http://en.wikipedia.org/> a dctypes:Text . "
            + "<http://example.org/software1> a <http://www.example.org/MySoftwareAgent> ; "
            + "foaf:name \"Demo software\" ."
            + "}";
    public static final String OA_NO_PERSON = "@prefix oa: <http://www.w3.org/ns/oa#> . " 
            + "@prefix foaf: <http://xmlns.com/foaf/0.1/> . "
            + "@prefix dctypes: <http://purl.org/dc/dcmitype/> . "
            + "<http://localhost:8080/lorestore/oa/sopabasic> { "
            + "<http://localhost:8080/lorestore/oa/sopabasic> a oa:Annotation ; "
            + "oa:annotatedBy <http://example.org/user1> ; "
            + "oa:annotatedAt \"2012-02-12T15:02:14Z\" ; "
            + "oa:motivatedBy oa:commenting ; "
            + "oa:hasBody <http://www.youtube.com/watch?v=uPh81LIe7B8> ; "
            + "oa:hasTarget <http://en.wikipedia.org/> ."
            + "<http://example.org/user1> a <http://www.example.org/Foo> ; "
            + "foaf:name \"Joe Bloggs\" . "
            + "<http://www.youtube.com/watch?v=uPh81LIe7B8> a dctypes:MovingImage ."
            + "<http://en.wikipedia.org/> a dctypes:Text . "
            + "}";
    public static final String OA_NO_AGENT_NAME = "@prefix oa: <http://www.w3.org/ns/oa#> . " 
            + "@prefix foaf: <http://xmlns.com/foaf/0.1/> . "
            + "@prefix dctypes: <http://purl.org/dc/dcmitype/> . "
            + "<http://localhost:8080/lorestore/oa/sopabasic> { "
            + "<http://localhost:8080/lorestore/oa/sopabasic> a oa:Annotation ; "
            + "oa:annotatedBy <http://example.org/user1> ; "
            + "oa:annotatedAt \"2012-02-12T15:02:14Z\" ; "
            + "oa:motivatedBy oa:commenting ; "
            + "oa:hasBody <http://www.youtube.com/watch?v=uPh81LIe7B8> ; "
            + "oa:hasTarget <http://en.wikipedia.org/> ."
            + "<http://example.org/user1> a foaf:Person . "
            + "<http://www.youtube.com/watch?v=uPh81LIe7B8> a dctypes:MovingImage ."
            + "<http://en.wikipedia.org/> a dctypes:Text . "
            + "}";
    public static final String OA_MULTIPLE_AGENT_NAME = "@prefix oa: <http://www.w3.org/ns/oa#> . " 
            + "@prefix foaf: <http://xmlns.com/foaf/0.1/> . "
            + "@prefix dctypes: <http://purl.org/dc/dcmitype/> . "
            + "<http://localhost:8080/lorestore/oa/sopabasic> { "
            + "<http://localhost:8080/lorestore/oa/sopabasic> a oa:Annotation ; "
            + "oa:annotatedBy <http://example.org/user1> ; "
            + "oa:annotatedAt \"2012-02-12T15:02:14Z\" ; "
            + "oa:motivatedBy oa:commenting ; "
            + "oa:hasBody <http://www.youtube.com/watch?v=uPh81LIe7B8> ; "
            + "oa:hasTarget <http://en.wikipedia.org/> ."
            + "<http://example.org/user1> a foaf:Person ; "
            + "foaf:name \"Joe Bloggs\" ; "
            + "foaf:name \"Mary Smith\" . "
            + "<http://www.youtube.com/watch?v=uPh81LIe7B8> a dctypes:MovingImage ."
            + "<http://en.wikipedia.org/> a dctypes:Text . "
            + "}";
    public static final String OA_MULTIPLE_SERIALIZEDAT = "@prefix oa: <http://www.w3.org/ns/oa#> ."
            + "<http://localhost:8080/lorestore/oa/sopabasic> {"
            + "<http://localhost:8080/lorestore/oa/sopabasic> a oa:Annotation ; "
            + "oa:serializedAt \"2012-02-12T15:02:14Z\" ; "
            + "oa:serializedAt \"2012-03-12T15:02:14Z\" ; "
            + "oa:hasBody <http://www.youtube.com/watch?v=uPh81LIe7B8> ; " 
            + "oa:hasTarget <http://en.wikipedia.org/> .}";
    
    public static final String OA_BASIC_INVALID_DATETIME = "@prefix oa: <http://www.w3.org/ns/oa#> . " 
            + "@prefix foaf: <http://xmlns.com/foaf/0.1/> . "
            + "@prefix dctypes: <http://purl.org/dc/dcmitype/> . "
            + "<http://localhost:8080/lorestore/oa/sopabasic> { "
            + "<http://localhost:8080/lorestore/oa/sopabasic> a oa:Annotation ; "
            + "oa:annotatedBy <http://example.org/user1> ; "
            + "oa:annotatedAt \"12 / 02 / 2012\" ; "
            + "oa:motivatedBy oa:commenting ; "
            + "oa:hasBody <http://www.youtube.com/watch?v=uPh81LIe7B8> ; "
            + "oa:hasTarget <http://en.wikipedia.org/> ."
            + "<http://example.org/user1> a foaf:Person ; "
            + "foaf:name \"Joe Bloggs\" . "
            + "<http://www.youtube.com/watch?v=uPh81LIe7B8> a dctypes:MovingImage ."
            + "<http://en.wikipedia.org/> a dctypes:Text . "
            + "}";
    public static final String OA_MULTIPLE_ANNOTATEDAT = "@prefix oa: <http://www.w3.org/ns/oa#> . " 
            + "@prefix foaf: <http://xmlns.com/foaf/0.1/> . "
            + "@prefix dctypes: <http://purl.org/dc/dcmitype/> . "
            + "<http://localhost:8080/lorestore/oa/sopabasic> { "
            + "<http://localhost:8080/lorestore/oa/sopabasic> a oa:Annotation ; "
            + "oa:annotatedBy <http://example.org/user1> ; "
            + "oa:annotatedAt \"2012-02-12T15:02:14Z\" ; "
            + "oa:annotatedAt \"2012-03-12T15:02:14Z\" ; "
            + "oa:motivatedBy oa:commenting ; "
            + "oa:hasBody <http://www.youtube.com/watch?v=uPh81LIe7B8> ; "
            + "oa:hasTarget <http://en.wikipedia.org/> ."
            + "<http://example.org/user1> a foaf:Person ; "
            + "foaf:name \"Joe Bloggs\" . "
            + "<http://www.youtube.com/watch?v=uPh81LIe7B8> a dctypes:MovingImage ."
            + "<http://en.wikipedia.org/> a dctypes:Text . "
            + "}";
   
    public static final String OA_NO_TYPE = "@prefix oa: <http://www.w3.org/ns/oa#> . " 
            + "@prefix foaf: <http://xmlns.com/foaf/0.1/> . "
            + "@prefix dctypes: <http://purl.org/dc/dcmitype/> . "
            + "<http://localhost:8080/lorestore/oa/sopabasic> { "
            + "<http://localhost:8080/lorestore/oa/sopabasic> oa:annotatedBy <http://example.org/user1> ; "
            + "oa:annotatedAt \"2012-02-12T15:02:14Z\" ; "
            + "oa:motivatedBy oa:commenting ; "
            + "oa:hasBody <http://www.youtube.com/watch?v=uPh81LIe7B8> ; "
            + "oa:hasTarget <http://en.wikipedia.org/> ."
            + "<http://example.org/user1> a foaf:Person ; "
            + "foaf:name \"Joe Bloggs\" . "
            + "<http://www.youtube.com/watch?v=uPh81LIe7B8> a dctypes:MovingImage ."
            + "<http://en.wikipedia.org/> a dctypes:Text . "
            + "}";
    public static final String OA_CUSTOM_SUBCLASS = "@prefix oa: <http://www.w3.org/ns/oa#> . " 
            + "@prefix foaf: <http://xmlns.com/foaf/0.1/> . "
            + "@prefix dctypes: <http://purl.org/dc/dcmitype/> . "
            + "@prefix ex: <http://example.org/> ."
            + "@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> ."
            + "<http://localhost:8080/lorestore/oa/sopabasic> { "
            + "<http://localhost:8080/lorestore/oa/sopabasic> a ex:MyAnnotation ; "
            + "oa:annotatedBy <http://example.org/user1> ; "
            + "oa:annotatedAt \"2012-02-12T15:02:14Z\" ; "
            + "oa:motivatedBy oa:commenting ; "
            + "oa:hasBody <http://www.youtube.com/watch?v=uPh81LIe7B8> ; "
            + "oa:hasTarget <http://en.wikipedia.org/> ."
            + "<http://example.org/user1> a foaf:Person ; "
            + "foaf:name \"Joe Bloggs\" . "
            + "<http://www.youtube.com/watch?v=uPh81LIe7B8> a dctypes:MovingImage ."
            + "<http://en.wikipedia.org/> a dctypes:Text . "
            + "ex:MyAnnotation rdfs:subClassOf oa:Annotation ."
            + "}";
    public static final String OA_CUSTOM_CLASS = "@prefix oa: <http://www.w3.org/ns/oa#> . " 
            + "@prefix foaf: <http://xmlns.com/foaf/0.1/> . "
            + "@prefix dctypes: <http://purl.org/dc/dcmitype/> . "
            + "@prefix ex: <http://example.org/> ."
            + "<http://localhost:8080/lorestore/oa/sopabasic> { "
            + "<http://localhost:8080/lorestore/oa/sopabasic> a ex:MyAnnotation ; "
            + "oa:annotatedBy <http://example.org/user1> ; "
            + "oa:annotatedAt \"2012-02-12T15:02:14Z\" ; "
            + "oa:motivatedBy oa:commenting ; "
            + "oa:hasBody <http://www.youtube.com/watch?v=uPh81LIe7B8> ; "
            + "oa:hasTarget <http://en.wikipedia.org/> ."
            + "<http://example.org/user1> a foaf:Person ; "
            + "foaf:name \"Joe Bloggs\" . "
            + "<http://www.youtube.com/watch?v=uPh81LIe7B8> a dctypes:MovingImage ."
            + "<http://en.wikipedia.org/> a dctypes:Text . "
            + "}";
    public static final String OA_NO_BODY = "@prefix oa: <http://www.w3.org/ns/oa#> . " 
            + "@prefix foaf: <http://xmlns.com/foaf/0.1/> . "
            + "@prefix dctypes: <http://purl.org/dc/dcmitype/> . "
            + "<http://localhost:8080/lorestore/oa/sopabasic> { "
            + "<http://localhost:8080/lorestore/oa/sopabasic> a oa:Annotation ; "
            + "oa:annotatedBy <http://example.org/user1> ; "
            + "oa:annotatedAt \"2012-02-12T15:02:14Z\" ; "
            + "oa:motivatedBy oa:commenting ; "
            + "oa:hasTarget <http://en.wikipedia.org/> ."
            + "<http://example.org/user1> a foaf:Person ; "
            + "foaf:name \"Joe Bloggs\" . "
            + "<http://en.wikipedia.org/> a dctypes:Text . "
            + "}";
    public static final String OA_BLANKNODE_TARGET = "@prefix oa: <http://www.w3.org/ns/oa#> . " 
            + "@prefix foaf: <http://xmlns.com/foaf/0.1/> . "
            + "@prefix dctypes: <http://purl.org/dc/dcmitype/> . "
            + "<http://localhost:8080/lorestore/oa/sopabasic> { "
            + "<http://localhost:8080/lorestore/oa/sopabasic> a oa:Annotation ; "
            + "oa:annotatedBy <http://example.org/user1> ; "
            + "oa:annotatedAt \"2012-02-12T15:02:14Z\" ; "
            + "oa:motivatedBy oa:commenting ; "
            + "oa:hasTarget _:yt ; "
            + "oa:hasBody <http://en.wikipedia.org/> ."
            + "<http://example.org/user1> a foaf:Person ; "
            + "foaf:name \"Joe Bloggs\" . "
            + "_:yt a dctypes:MovingImage ."
            + "<http://en.wikipedia.org/> a dctypes:Text . "
            + "}";
    public static final String OA_UUID_BODY = "@prefix oa: <http://www.w3.org/ns/oa#> . " 
            + "@prefix foaf: <http://xmlns.com/foaf/0.1/> . "
            + "@prefix dctypes: <http://purl.org/dc/dcmitype/> . "
            + "<http://localhost:8080/lorestore/oa/sopabasic> { "
            + "<http://localhost:8080/lorestore/oa/sopabasic> a oa:Annotation ; "
            + "oa:annotatedBy <http://example.org/user1> ; "
            + "oa:annotatedAt \"2012-02-12T15:02:14Z\" ; "
            + "oa:motivatedBy oa:commenting ; "
            + "oa:hasBody <urn:uuid:e199e350-0eaf-11e1-be50-0800200c9a66> ; "
            + "oa:hasTarget <http://en.wikipedia.org/> ."
            + "<http://example.org/user1> a foaf:Person ; "
            + "foaf:name \"Joe Bloggs\" . "
            + "<urn:uuid:e199e350-0eaf-11e1-be50-0800200c9a66> a dctypes:MovingImage ."
            + "<http://en.wikipedia.org/> a dctypes:Text . "
            + "}";
    
    public static final String OA_EMBEDDED_BODY = "@prefix oa: <http://www.w3.org/ns/oa#> . " 
            + "@prefix foaf: <http://xmlns.com/foaf/0.1/> . "
            + "@prefix dctypes: <http://purl.org/dc/dcmitype/> . "
            + "@prefix cnt: <http://www.w3.org/2011/content#> ."
            + "@prefix dc: <http://purl.org/dc/elements/1.1/> ."
            + "<http://localhost:8080/lorestore/oa/sopabasic> { "
            + "<http://localhost:8080/lorestore/oa/sopabasic> a oa:Annotation ; "
            + "oa:annotatedBy <http://example.org/user1> ; "
            + "oa:annotatedAt \"2012-02-12T15:02:14Z\" ; "
            + "oa:motivatedBy oa:commenting ; "
            + "oa:hasBody <urn:uuid:b42b3210-9686-11e2-9e96-0800200c9a66> ; "
            + "oa:hasTarget <http://en.wikipedia.org/> ."
            + "<http://example.org/user1> a foaf:Person ; "
            + "foaf:name \"Joe Bloggs\" . "
            + "<http://www.youtube.com/watch?v=uPh81LIe7B8> a dctypes:MovingImage ."
            + "<http://en.wikipedia.org/> a dctypes:Text . "
            + "<urn:uuid:b42b3210-9686-11e2-9e96-0800200c9a66> a cnt:ContentAsText, dctypes:Text ; "
            + "cnt:chars \"content\" ; "
            + "dc:language \"en-US\" ; "
            + "cnt:characterEncoding \"UTF-8\" ; "
            + "dc:format \"text/plain\" . "
            + "}";
    public static final String OA_EMBEDDED_BODY_NONRFC3066_LANGUAGE = "@prefix oa: <http://www.w3.org/ns/oa#> . " 
            + "@prefix foaf: <http://xmlns.com/foaf/0.1/> . "
            + "@prefix dctypes: <http://purl.org/dc/dcmitype/> . "
            + "@prefix cnt: <http://www.w3.org/2011/content#> ."
            + "@prefix dc: <http://purl.org/dc/elements/1.1/> ."
            + "<http://localhost:8080/lorestore/oa/sopabasic> { "
            + "<http://localhost:8080/lorestore/oa/sopabasic> a oa:Annotation ; "
            + "oa:annotatedBy <http://example.org/user1> ; "
            + "oa:annotatedAt \"2012-02-12T15:02:14Z\" ; "
            + "oa:motivatedBy oa:commenting ; "
            + "oa:hasBody <urn:uuid:b42b3210-9686-11e2-9e96-0800200c9a66> ; "
            + "oa:hasTarget <http://en.wikipedia.org/> ."
            + "<http://example.org/user1> a foaf:Person ; "
            + "foaf:name \"Joe Bloggs\" . "
            + "<http://www.youtube.com/watch?v=uPh81LIe7B8> a dctypes:MovingImage ."
            + "<http://en.wikipedia.org/> a dctypes:Text . "
            + "<urn:uuid:b42b3210-9686-11e2-9e96-0800200c9a66> a cnt:ContentAsText, dctypes:Text ; "
            + "cnt:chars \"content\" ; "
            + "dc:language \"Klingon\" ; "
            + "cnt:characterEncoding \"UTF-8\" ; "
            + "dc:format \"text/plain\" . "
            + "}";
    public static final String OA_EMBEDDED_BODY_NO_CONTENTASTEXT = "@prefix oa: <http://www.w3.org/ns/oa#> . " 
            + "@prefix foaf: <http://xmlns.com/foaf/0.1/> . "
            + "@prefix dctypes: <http://purl.org/dc/dcmitype/> . "
            + "@prefix cnt: <http://www.w3.org/2011/content#> ."
            + "@prefix dc: <http://purl.org/dc/elements/1.1/> ."
            + "<http://localhost:8080/lorestore/oa/sopabasic> { "
            + "<http://localhost:8080/lorestore/oa/sopabasic> a oa:Annotation ; "
            + "oa:annotatedBy <http://example.org/user1> ; "
            + "oa:annotatedAt \"2012-02-12T15:02:14Z\" ; "
            + "oa:motivatedBy oa:commenting ; "
            + "oa:hasBody <urn:uuid:b42b3210-9686-11e2-9e96-0800200c9a66> ; "
            + "oa:hasTarget <http://en.wikipedia.org/> ."
            + "<http://example.org/user1> a foaf:Person ; "
            + "foaf:name \"Joe Bloggs\" . "
            + "<http://www.youtube.com/watch?v=uPh81LIe7B8> a dctypes:MovingImage ."
            + "<http://en.wikipedia.org/> a dctypes:Text . "
            + "<urn:uuid:b42b3210-9686-11e2-9e96-0800200c9a66> a dctypes:Text ; "
            + "cnt:chars \"content\" ; "
            + "cnt:characterEncoding \"UTF-8\" ; "
            + "dc:format \"text/plain\" . "
            + "}";
    public static final String OA_EMBEDDED_BODY_NO_FORMAT = "@prefix oa: <http://www.w3.org/ns/oa#> . " 
            + "@prefix foaf: <http://xmlns.com/foaf/0.1/> . "
            + "@prefix dctypes: <http://purl.org/dc/dcmitype/> . "
            + "@prefix cnt: <http://www.w3.org/2011/content#> ."
            + "@prefix dc: <http://purl.org/dc/elements/1.1/> ."
            + "<http://localhost:8080/lorestore/oa/sopabasic> { "
            + "<http://localhost:8080/lorestore/oa/sopabasic> a oa:Annotation ; "
            + "oa:annotatedBy <http://example.org/user1> ; "
            + "oa:annotatedAt \"2012-02-12T15:02:14Z\" ; "
            + "oa:motivatedBy oa:commenting ; "
            + "oa:hasBody <urn:uuid:b42b3210-9686-11e2-9e96-0800200c9a66> ; "
            + "oa:hasTarget <http://en.wikipedia.org/> ."
            + "<http://example.org/user1> a foaf:Person ; "
            + "foaf:name \"Joe Bloggs\" . "
            + "<http://www.youtube.com/watch?v=uPh81LIe7B8> a dctypes:MovingImage ."
            + "<http://en.wikipedia.org/> a dctypes:Text . "
            + "<urn:uuid:b42b3210-9686-11e2-9e96-0800200c9a66> a cnt:ContentAsText, dctypes:Text ; "
            + "cnt:chars \"content\" ; "
            + "cnt:characterEncoding \"UTF-8\" . "
            + "}";
    public static final String OA_EMBEDDED_BODY_NO_ENCODING_OR_CHARS = "@prefix oa: <http://www.w3.org/ns/oa#> . " 
            + "@prefix foaf: <http://xmlns.com/foaf/0.1/> . "
            + "@prefix dctypes: <http://purl.org/dc/dcmitype/> . "
            + "@prefix cnt: <http://www.w3.org/2011/content#> ."
            + "@prefix dc: <http://purl.org/dc/elements/1.1/> ."
            + "<http://localhost:8080/lorestore/oa/sopabasic> { "
            + "<http://localhost:8080/lorestore/oa/sopabasic> a oa:Annotation ; "
            + "oa:annotatedBy <http://example.org/user1> ; "
            + "oa:annotatedAt \"2012-02-12T15:02:14Z\" ; "
            + "oa:motivatedBy oa:commenting ; "
            + "oa:hasBody <urn:uuid:b42b3210-9686-11e2-9e96-0800200c9a66> ; "
            + "oa:hasTarget <http://en.wikipedia.org/> ."
            + "<http://example.org/user1> a foaf:Person ; "
            + "foaf:name \"Joe Bloggs\" . "
            + "<http://www.youtube.com/watch?v=uPh81LIe7B8> a dctypes:MovingImage ."
            + "<http://en.wikipedia.org/> a dctypes:Text . "
            + "<urn:uuid:b42b3210-9686-11e2-9e96-0800200c9a66> a cnt:ContentAsText, dctypes:Text ; "
            + "dc:format \"text/plain\" . "
            + "}";
    public static final String OA_EMBEDDED_BODY_MULTIPLE_CHARS = "@prefix oa: <http://www.w3.org/ns/oa#> . " 
            + "@prefix foaf: <http://xmlns.com/foaf/0.1/> . "
            + "@prefix dctypes: <http://purl.org/dc/dcmitype/> . "
            + "@prefix cnt: <http://www.w3.org/2011/content#> ."
            + "@prefix dc: <http://purl.org/dc/elements/1.1/> ."
            + "<http://localhost:8080/lorestore/oa/sopabasic> { "
            + "<http://localhost:8080/lorestore/oa/sopabasic> a oa:Annotation ; "
            + "oa:annotatedBy <http://example.org/user1> ; "
            + "oa:annotatedAt \"2012-02-12T15:02:14Z\" ; "
            + "oa:motivatedBy oa:commenting ; "
            + "oa:hasBody <urn:uuid:b42b3210-9686-11e2-9e96-0800200c9a66> ; "
            + "oa:hasTarget <http://en.wikipedia.org/> ."
            + "<http://example.org/user1> a foaf:Person ; "
            + "foaf:name \"Joe Bloggs\" . "
            + "<http://www.youtube.com/watch?v=uPh81LIe7B8> a dctypes:MovingImage ."
            + "<http://en.wikipedia.org/> a dctypes:Text . "
            + "<urn:uuid:b42b3210-9686-11e2-9e96-0800200c9a66> a cnt:ContentAsText, dctypes:Text ; "
            + "cnt:chars \"content\" ; "
            + "cnt:chars \"another content\" ; "
            + "cnt:characterEncoding \"UTF-8\" ; "
            + "dc:format \"text/plain\" . "
            + "}";
    public static final String OA_EMBEDDED_BODY_BASE64 = "@prefix oa: <http://www.w3.org/ns/oa#> . " 
            + "@prefix foaf: <http://xmlns.com/foaf/0.1/> . "
            + "@prefix dctypes: <http://purl.org/dc/dcmitype/> . "
            + "@prefix cnt: <http://www.w3.org/2011/content#> ."
            + "@prefix dc: <http://purl.org/dc/elements/1.1/> ."
            + "<http://localhost:8080/lorestore/oa/sopabasic> { "
            + "<http://localhost:8080/lorestore/oa/sopabasic> a oa:Annotation ; "
            + "oa:annotatedBy <http://example.org/user1> ; "
            + "oa:annotatedAt \"2012-02-12T15:02:14Z\" ; "
            + "oa:motivatedBy oa:commenting ; "
            + "oa:hasBody <urn:uuid:b42b3210-9686-11e2-9e96-0800200c9a66> ; "
            + "oa:hasTarget <http://en.wikipedia.org/> ."
            + "<http://example.org/user1> a foaf:Person ; "
            + "foaf:name \"Joe Bloggs\" . "
            + "<http://www.youtube.com/watch?v=uPh81LIe7B8> a dctypes:MovingImage ."
            + "<http://en.wikipedia.org/> a dctypes:Text . "
            + "<urn:uuid:b42b3210-9686-11e2-9e96-0800200c9a66> a cnt:ContentAsBase64 ; "
            + "cnt:bytes \"foo\" ; "
            + "cnt:characterEncoding \"UTF-8\" ; "
            + "dc:format \"text/plain\" . "
            + "}";
    public static final String OA_EMBEDDED_BODY_BASE64_MULTIPLE_BYTES = "@prefix oa: <http://www.w3.org/ns/oa#> . " 
            + "@prefix foaf: <http://xmlns.com/foaf/0.1/> . "
            + "@prefix dctypes: <http://purl.org/dc/dcmitype/> . "
            + "@prefix cnt: <http://www.w3.org/2011/content#> ."
            + "@prefix dc: <http://purl.org/dc/elements/1.1/> ."
            + "<http://localhost:8080/lorestore/oa/sopabasic> { "
            + "<http://localhost:8080/lorestore/oa/sopabasic> a oa:Annotation ; "
            + "oa:annotatedBy <http://example.org/user1> ; "
            + "oa:annotatedAt \"2012-02-12T15:02:14Z\" ; "
            + "oa:motivatedBy oa:commenting ; "
            + "oa:hasBody <urn:uuid:b42b3210-9686-11e2-9e96-0800200c9a66> ; "
            + "oa:hasTarget <http://en.wikipedia.org/> ."
            + "<http://example.org/user1> a foaf:Person ; "
            + "foaf:name \"Joe Bloggs\" . "
            + "<http://www.youtube.com/watch?v=uPh81LIe7B8> a dctypes:MovingImage ."
            + "<http://en.wikipedia.org/> a dctypes:Text . "
            + "<urn:uuid:b42b3210-9686-11e2-9e96-0800200c9a66> a cnt:ContentAsBase64 ; "
            + "cnt:bytes \"foo\" ; "
            + "cnt:bytes \"bar\" ; "
            + "cnt:characterEncoding \"UTF-8\" ; "
            + "dc:format \"text/plain\" . "
            + "}";
    public static final String OA_EMBEDDED_BODY_BASE64_NO_BYTES = "@prefix oa: <http://www.w3.org/ns/oa#> . " 
            + "@prefix foaf: <http://xmlns.com/foaf/0.1/> . "
            + "@prefix dctypes: <http://purl.org/dc/dcmitype/> . "
            + "@prefix cnt: <http://www.w3.org/2011/content#> ."
            + "@prefix dc: <http://purl.org/dc/elements/1.1/> ."
            + "<http://localhost:8080/lorestore/oa/sopabasic> { "
            + "<http://localhost:8080/lorestore/oa/sopabasic> a oa:Annotation ; "
            + "oa:annotatedBy <http://example.org/user1> ; "
            + "oa:annotatedAt \"2012-02-12T15:02:14Z\" ; "
            + "oa:motivatedBy oa:commenting ; "
            + "oa:hasBody <urn:uuid:b42b3210-9686-11e2-9e96-0800200c9a66> ; "
            + "oa:hasTarget <http://en.wikipedia.org/> ."
            + "<http://example.org/user1> a foaf:Person ; "
            + "foaf:name \"Joe Bloggs\" . "
            + "<http://www.youtube.com/watch?v=uPh81LIe7B8> a dctypes:MovingImage ."
            + "<http://en.wikipedia.org/> a dctypes:Text . "
            + "<urn:uuid:b42b3210-9686-11e2-9e96-0800200c9a66> a cnt:ContentAsBase64 ; "
            + "cnt:characterEncoding \"UTF-8\" ; "
            + "dc:format \"text/plain\" . "
            + "}";
    public static final String OA_EMBEDDED_BODY_MULTIPLE_ENCODING = "@prefix oa: <http://www.w3.org/ns/oa#> . " 
            + "@prefix foaf: <http://xmlns.com/foaf/0.1/> . "
            + "@prefix dctypes: <http://purl.org/dc/dcmitype/> . "
            + "@prefix cnt: <http://www.w3.org/2011/content#> ."
            + "@prefix dc: <http://purl.org/dc/elements/1.1/> ."
            + "<http://localhost:8080/lorestore/oa/sopabasic> { "
            + "<http://localhost:8080/lorestore/oa/sopabasic> a oa:Annotation ; "
            + "oa:annotatedBy <http://example.org/user1> ; "
            + "oa:annotatedAt \"2012-02-12T15:02:14Z\" ; "
            + "oa:motivatedBy oa:commenting ; "
            + "oa:hasBody <urn:uuid:b42b3210-9686-11e2-9e96-0800200c9a66> ; "
            + "oa:hasTarget <http://en.wikipedia.org/> ."
            + "<http://example.org/user1> a foaf:Person ; "
            + "foaf:name \"Joe Bloggs\" . "
            + "<http://www.youtube.com/watch?v=uPh81LIe7B8> a dctypes:MovingImage ."
            + "<http://en.wikipedia.org/> a dctypes:Text . "
            + "<urn:uuid:b42b3210-9686-11e2-9e96-0800200c9a66> a cnt:ContentAsText, dctypes:Text ; "
            + "cnt:chars \"content\" ; "
            + "cnt:characterEncoding \"UTF-8\" ; "
            + "cnt:characterEncoding \"foo\" ; "
            + "dc:format \"text/plain\" . "
            + "}";
    public static final String OA_IMAGE_AS_TEXT = "@prefix oa: <http://www.w3.org/ns/oa#> . " 
            + "@prefix foaf: <http://xmlns.com/foaf/0.1/> . "
            + "@prefix dctypes: <http://purl.org/dc/dcmitype/> . "
            + "<http://localhost:8080/lorestore/oa/sopabasic> { "
            + "<http://localhost:8080/lorestore/oa/sopabasic> a oa:Annotation ; "
            + "oa:annotatedBy <http://example.org/user1> ; "
            + "oa:annotatedAt \"2012-02-12T15:02:14Z\" ; "
            + "oa:motivatedBy oa:commenting ; "
            + "oa:hasBody <http://www.youtube.com/watch?v=uPh81LIe7B8> ; "
            + "oa:hasTarget <http://www.example.org/MyImageOfText.jpg> ."
            + "<http://example.org/user1> a foaf:Person ; "
            + "foaf:name \"Joe Bloggs\" . "
            + "<http://www.youtube.com/watch?v=uPh81LIe7B8> a dctypes:MovingImage ."
            + "<http://www.example.org/MyImageOfText.jpg> a dctypes:Text . "
            + "}";
    public static final String OA_IMAGE_AS_IMAGE = "@prefix oa: <http://www.w3.org/ns/oa#> . " 
            + "@prefix foaf: <http://xmlns.com/foaf/0.1/> . "
            + "@prefix dctypes: <http://purl.org/dc/dcmitype/> . "
            + "<http://localhost:8080/lorestore/oa/sopabasic> { "
            + "<http://localhost:8080/lorestore/oa/sopabasic> a oa:Annotation ; "
            + "oa:annotatedBy <http://example.org/user1> ; "
            + "oa:annotatedAt \"2012-02-12T15:02:14Z\" ; "
            + "oa:motivatedBy oa:commenting ; "
            + "oa:hasBody <http://www.youtube.com/watch?v=uPh81LIe7B8> ; "
            + "oa:hasTarget <http://www.example.org/MyImageOfText.jpg> ."
            + "<http://example.org/user1> a foaf:Person ; "
            + "foaf:name \"Joe Bloggs\" . "
            + "<http://www.youtube.com/watch?v=uPh81LIe7B8> a dctypes:MovingImage ."
            + "<http://www.example.org/MyImageOfText.jpg> a dctypes:Image . "
            + "}";
    public static final String OA_NO_TARGET = "@prefix oa: <http://www.w3.org/ns/oa#> . " 
            + "@prefix foaf: <http://xmlns.com/foaf/0.1/> . "
            + "@prefix dctypes: <http://purl.org/dc/dcmitype/> . "
            + "<http://localhost:8080/lorestore/oa/sopabasic> { "
            + "<http://localhost:8080/lorestore/oa/sopabasic> a oa:Annotation ; "
            + "oa:annotatedBy <http://example.org/user1> ; "
            + "oa:annotatedAt \"2012-02-12T15:02:14Z\" ; "
            + "oa:motivatedBy oa:commenting ; "
            + "oa:hasBody <http://www.youtube.com/watch?v=uPh81LIe7B8> . "
            + "<http://example.org/user1> a foaf:Person ; "
            + "foaf:name \"Joe Bloggs\" . "
            + "<http://www.youtube.com/watch?v=uPh81LIe7B8> a dctypes:MovingImage ."
            + "}";
    public static final String OA_FRAGMENT_TARGET = "@prefix oa: <http://www.w3.org/ns/oa#> . " 
            + "@prefix foaf: <http://xmlns.com/foaf/0.1/> . "
            + "@prefix dctypes: <http://purl.org/dc/dcmitype/> . "
            + "<http://localhost:8080/lorestore/oa/sopabasic> { "
            + "<http://localhost:8080/lorestore/oa/sopabasic> a oa:Annotation ; "
            + "oa:annotatedBy <http://example.org/user1> ; "
            + "oa:annotatedAt \"2012-02-12T15:02:14Z\" ; "
            + "oa:motivatedBy oa:commenting ; "
            + "oa:hasTarget <http://www.example.org/mypage.html#foo> ;"
            + "oa:hasBody <http://www.youtube.com/watch?v=uPh81LIe7B8> . "
            + "<http://example.org/user1> a foaf:Person ; "
            + "foaf:name \"Joe Bloggs\" . "
            + "<http://www.youtube.com/watch?v=uPh81LIe7B8> a dctypes:MovingImage ."
            + "<http://www.example.org/mypage.html#foo> a dctypes:Text ."
            + "}";
    public static final String OA_FRAGMENT_SELECTOR = "@prefix oa: <http://www.w3.org/ns/oa#> . " 
            + "@prefix foaf: <http://xmlns.com/foaf/0.1/> . "
            + "@prefix dctypes: <http://purl.org/dc/dcmitype/> . "
            + "@prefix dcterms: <http://purl.org/dc/terms/> . "
            + "<http://localhost:8080/lorestore/oa/sopabasic> { "
            + "<http://localhost:8080/lorestore/oa/sopabasic> a oa:Annotation ; "
            + "oa:annotatedBy <http://example.org/user1> ; "
            + "oa:annotatedAt \"2012-02-12T15:02:14Z\" ; "
            + "oa:motivatedBy oa:commenting ; "
            + "oa:hasTarget <urn:uuid:89ef7820-9687-11e2-9e96-0800200c9a66> ;"
            + "oa:hasBody <http://www.youtube.com/watch?v=uPh81LIe7B8> . "
            + "<urn:uuid:0bf18730-96a3-11e2-9e96-0800200c9a66> a oa:FragmentSelector ; "
            + "dcterms:conformsTo <http://tools.ietf.org/rfc/rfc3236> ; "
            + "rdf:value \"#foo\" . "
            + "<urn:uuid:89ef7820-9687-11e2-9e96-0800200c9a66> a oa:SpecificResource ; "
            + "oa:hasSelector <urn:uuid:0bf18730-96a3-11e2-9e96-0800200c9a66> ; "
            + "oa:hasSource <http://www.example.org/mypage.html> . "
            + "<http://example.org/user1> a foaf:Person ; "
            + "foaf:name \"Joe Bloggs\" . "
            + "<http://www.youtube.com/watch?v=uPh81LIe7B8> a dctypes:MovingImage ."
            + "<http://www.example.org/mypage.html> a dctypes:Text ."
            + "}";
    public static final String OA_TEXTPOSSEL_NO_START_OR_END = "@prefix oa: <http://www.w3.org/ns/oa#> . " 
            + "@prefix foaf: <http://xmlns.com/foaf/0.1/> . "
            + "@prefix dctypes: <http://purl.org/dc/dcmitype/> . "
            + "@prefix dcterms: <http://purl.org/dc/terms/> . "
            + "<http://localhost:8080/lorestore/oa/sopabasic> { "
            + "<http://localhost:8080/lorestore/oa/sopabasic> a oa:Annotation ; "
            + "oa:annotatedBy <http://example.org/user1> ; "
            + "oa:annotatedAt \"2012-02-12T15:02:14Z\" ; "
            + "oa:motivatedBy oa:commenting ; "
            + "oa:hasTarget <urn:uuid:89ef7820-9687-11e2-9e96-0800200c9a66> ;"
            + "oa:hasBody <http://www.youtube.com/watch?v=uPh81LIe7B8> . "
            + "<urn:uuid:0bf18730-96a3-11e2-9e96-0800200c9a66> a oa:TextPositionSelector . "
            + "<urn:uuid:89ef7820-9687-11e2-9e96-0800200c9a66> a oa:SpecificResource ; "
            + "oa:hasSelector <urn:uuid:0bf18730-96a3-11e2-9e96-0800200c9a66> ; "
            + "oa:hasSource <http://www.example.org/mypage.html> . "
            + "<http://example.org/user1> a foaf:Person ; "
            + "foaf:name \"Joe Bloggs\" . "
            + "<http://www.youtube.com/watch?v=uPh81LIe7B8> a dctypes:MovingImage ."
            + "<http://www.example.org/mypage.html> a dctypes:Text ."
            + "}";
    public static final String OA_TEXTPOSSEL_MULTIPLE_START_OR_END = "@prefix oa: <http://www.w3.org/ns/oa#> . " 
            + "@prefix foaf: <http://xmlns.com/foaf/0.1/> . "
            + "@prefix dctypes: <http://purl.org/dc/dcmitype/> . "
            + "@prefix dcterms: <http://purl.org/dc/terms/> . "
            + "<http://localhost:8080/lorestore/oa/sopabasic> { "
            + "<http://localhost:8080/lorestore/oa/sopabasic> a oa:Annotation ; "
            + "oa:annotatedBy <http://example.org/user1> ; "
            + "oa:annotatedAt \"2012-02-12T15:02:14Z\" ; "
            + "oa:motivatedBy oa:commenting ; "
            + "oa:hasTarget <urn:uuid:89ef7820-9687-11e2-9e96-0800200c9a66> ;"
            + "oa:hasBody <http://www.youtube.com/watch?v=uPh81LIe7B8> . "
            + "<urn:uuid:0bf18730-96a3-11e2-9e96-0800200c9a66> a oa:TextPositionSelector ; "
            + "oa:start \"10\" ;"
            + "oa:start \"20\" ; "
            + "oa:end \"30\" ; "
            + "oa:end \"40\" . "
            + "<urn:uuid:89ef7820-9687-11e2-9e96-0800200c9a66> a oa:SpecificResource ; "
            + "oa:hasSelector <urn:uuid:0bf18730-96a3-11e2-9e96-0800200c9a66> ; "
            + "oa:hasSource <http://www.example.org/mypage.html> . "
            + "<http://example.org/user1> a foaf:Person ; "
            + "foaf:name \"Joe Bloggs\" . "
            + "<http://www.youtube.com/watch?v=uPh81LIe7B8> a dctypes:MovingImage ."
            + "<http://www.example.org/mypage.html> a dctypes:Text ."
            + "}";
    public static final String OA_TEXTPOSSEL_TIMESTATE = "@prefix oa: <http://www.w3.org/ns/oa#> . " 
            + "@prefix foaf: <http://xmlns.com/foaf/0.1/> . "
            + "@prefix dctypes: <http://purl.org/dc/dcmitype/> . "
            + "@prefix dcterms: <http://purl.org/dc/terms/> . "
            + "<http://localhost:8080/lorestore/oa/sopabasic> { "
            + "<http://localhost:8080/lorestore/oa/sopabasic> a oa:Annotation ; "
            + "oa:annotatedBy <http://example.org/user1> ; "
            + "oa:annotatedAt \"2012-02-12T15:02:14Z\" ; "
            + "oa:motivatedBy oa:commenting ; "
            + "oa:hasTarget <urn:uuid:89ef7820-9687-11e2-9e96-0800200c9a66> ;"
            + "oa:hasBody <http://www.youtube.com/watch?v=uPh81LIe7B8> . "
            + "<urn:uuid:0bf18730-96a3-11e2-9e96-0800200c9a66> a oa:TextPositionSelector ; "
            + "oa:start \"20\" ; "
            + "oa:end \"40\" . "
            + "<urn:uuid:89ef7820-9687-11e2-9e96-0800200c9a66> a oa:SpecificResource ; "
            + "oa:hasSelector <urn:uuid:0bf18730-96a3-11e2-9e96-0800200c9a66> ; "
            + "oa:hasState <urn:uuid:a30a2ca0-975a-11e2-9e96-0800200c9a66> ;"
            + "oa:hasSource <http://www.example.org/mypage.html> . "
            + "<http://example.org/user1> a foaf:Person ; "
            + "foaf:name \"Joe Bloggs\" . "
            + "<urn:uuid:a30a2ca0-975a-11e2-9e96-0800200c9a66> a oa:TimeState ; "
            + "oa:cachedSource <http:www.example.org/copy> ."
            + "<http://www.youtube.com/watch?v=uPh81LIe7B8> a dctypes:MovingImage ."
            + "<http://www.example.org/mypage.html> a dctypes:Text ."
            + "}";
    public static final String OA_TIMESTATE_NO_WHEN = "@prefix oa: <http://www.w3.org/ns/oa#> . " 
            + "@prefix foaf: <http://xmlns.com/foaf/0.1/> . "
            + "@prefix dctypes: <http://purl.org/dc/dcmitype/> . "
            + "@prefix dcterms: <http://purl.org/dc/terms/> . "
            + "<http://localhost:8080/lorestore/oa/sopabasic> { "
            + "<http://localhost:8080/lorestore/oa/sopabasic> a oa:Annotation ; "
            + "oa:annotatedBy <http://example.org/user1> ; "
            + "oa:annotatedAt \"2012-02-12T15:02:14Z\" ; "
            + "oa:motivatedBy oa:commenting ; "
            + "oa:hasTarget <urn:uuid:89ef7820-9687-11e2-9e96-0800200c9a66> ;"
            + "oa:hasBody <http://www.youtube.com/watch?v=uPh81LIe7B8> . "
            + "<urn:uuid:0bf18730-96a3-11e2-9e96-0800200c9a66> a oa:TextPositionSelector ; "
            + "oa:start \"20\" ; "
            + "oa:end \"40\" . "
            + "<urn:uuid:89ef7820-9687-11e2-9e96-0800200c9a66> a oa:SpecificResource ; "
            + "oa:hasSelector <urn:uuid:0bf18730-96a3-11e2-9e96-0800200c9a66> ; "
            + "oa:hasState <urn:uuid:a30a2ca0-975a-11e2-9e96-0800200c9a66> ;"
            + "oa:hasSource <http://www.example.org/mypage.html> . "
            + "<http://example.org/user1> a foaf:Person ; "
            + "foaf:name \"Joe Bloggs\" . "
            + "<urn:uuid:a30a2ca0-975a-11e2-9e96-0800200c9a66> a oa:TimeState . "
            + "<http://www.youtube.com/watch?v=uPh81LIe7B8> a dctypes:MovingImage ."
            + "<http://www.example.org/mypage.html> a dctypes:Text ."
            + "}";
    public static final String OA_TIMESTATE_INVALID_WHEN = "@prefix oa: <http://www.w3.org/ns/oa#> . " 
            + "@prefix foaf: <http://xmlns.com/foaf/0.1/> . "
            + "@prefix dctypes: <http://purl.org/dc/dcmitype/> . "
            + "@prefix dcterms: <http://purl.org/dc/terms/> . "
            + "<http://localhost:8080/lorestore/oa/sopabasic> { "
            + "<http://localhost:8080/lorestore/oa/sopabasic> a oa:Annotation ; "
            + "oa:annotatedBy <http://example.org/user1> ; "
            + "oa:annotatedAt \"2012-02-12T15:02:14Z\" ; "
            + "oa:motivatedBy oa:commenting ; "
            + "oa:hasTarget <urn:uuid:89ef7820-9687-11e2-9e96-0800200c9a66> ;"
            + "oa:hasBody <http://www.youtube.com/watch?v=uPh81LIe7B8> . "
            + "<urn:uuid:0bf18730-96a3-11e2-9e96-0800200c9a66> a oa:TextPositionSelector ; "
            + "oa:start \"20\" ; "
            + "oa:end \"40\" . "
            + "<urn:uuid:89ef7820-9687-11e2-9e96-0800200c9a66> a oa:SpecificResource ; "
            + "oa:hasSelector <urn:uuid:0bf18730-96a3-11e2-9e96-0800200c9a66> ; "
            + "oa:hasState <urn:uuid:a30a2ca0-975a-11e2-9e96-0800200c9a66> ;"
            + "oa:hasSource <http://www.example.org/mypage.html> . "
            + "<http://example.org/user1> a foaf:Person ; "
            + "foaf:name \"Joe Bloggs\" . "
            + "<urn:uuid:a30a2ca0-975a-11e2-9e96-0800200c9a66> a oa:TimeState ; "
            + "oa:when \"12/1/2013\" . "
            + "<http://www.youtube.com/watch?v=uPh81LIe7B8> a dctypes:MovingImage ."
            + "<http://www.example.org/mypage.html> a dctypes:Text ."
            + "}";
    public static final String OA_HTTPREQUESTSTATE_NO_VAL = "@prefix oa: <http://www.w3.org/ns/oa#> . " 
            + "@prefix foaf: <http://xmlns.com/foaf/0.1/> . "
            + "@prefix dctypes: <http://purl.org/dc/dcmitype/> . "
            + "@prefix dcterms: <http://purl.org/dc/terms/> . "
            + "<http://localhost:8080/lorestore/oa/sopabasic> { "
            + "<http://localhost:8080/lorestore/oa/sopabasic> a oa:Annotation ; "
            + "oa:annotatedBy <http://example.org/user1> ; "
            + "oa:annotatedAt \"2012-02-12T15:02:14Z\" ; "
            + "oa:motivatedBy oa:commenting ; "
            + "oa:hasTarget <urn:uuid:89ef7820-9687-11e2-9e96-0800200c9a66> ;"
            + "oa:hasBody <http://www.youtube.com/watch?v=uPh81LIe7B8> . "
            + "<urn:uuid:0bf18730-96a3-11e2-9e96-0800200c9a66> a oa:FragmentSelector ; "
            + "dcterms:conformsTo <http://tools.ietf.org/rfc/rfc3236> ; "
            + "rdf:value \"#foo\" . "
            + "<urn:uuid:89ef7820-9687-11e2-9e96-0800200c9a66> a oa:SpecificResource ; "
            + "oa:hasSelector <urn:uuid:0bf18730-96a3-11e2-9e96-0800200c9a66> ; "
            + "oa:hasState <urn:uuid:7645af80-975c-11e2-9e96-0800200c9a66> ;"
            + "oa:hasSource <http://www.example.org/mypage.html> . "
            + "<http://example.org/user1> a foaf:Person ; "
            + "foaf:name \"Joe Bloggs\" . "
            + "<http://www.youtube.com/watch?v=uPh81LIe7B8> a dctypes:MovingImage ."
            + "<http://www.example.org/mypage.html> a dctypes:Text ."
            + "<urn:uuid:7645af80-975c-11e2-9e96-0800200c9a66> a oa:HTTPRequestState ."
            + "}";
    public static final String OA_HTTPREQUESTSTATE_MULTIPLE_VAL = "@prefix oa: <http://www.w3.org/ns/oa#> . " 
            + "@prefix foaf: <http://xmlns.com/foaf/0.1/> . "
            + "@prefix dctypes: <http://purl.org/dc/dcmitype/> . "
            + "@prefix dcterms: <http://purl.org/dc/terms/> . "
            + "<http://localhost:8080/lorestore/oa/sopabasic> { "
            + "<http://localhost:8080/lorestore/oa/sopabasic> a oa:Annotation ; "
            + "oa:annotatedBy <http://example.org/user1> ; "
            + "oa:annotatedAt \"2012-02-12T15:02:14Z\" ; "
            + "oa:motivatedBy oa:commenting ; "
            + "oa:hasTarget <urn:uuid:89ef7820-9687-11e2-9e96-0800200c9a66> ;"
            + "oa:hasBody <http://www.youtube.com/watch?v=uPh81LIe7B8> . "
            + "<urn:uuid:0bf18730-96a3-11e2-9e96-0800200c9a66> a oa:FragmentSelector ; "
            + "dcterms:conformsTo <http://tools.ietf.org/rfc/rfc3236> ; "
            + "rdf:value \"#foo\" . "
            + "<urn:uuid:89ef7820-9687-11e2-9e96-0800200c9a66> a oa:SpecificResource ; "
            + "oa:hasSelector <urn:uuid:0bf18730-96a3-11e2-9e96-0800200c9a66> ; "
            + "oa:hasState <urn:uuid:7645af80-975c-11e2-9e96-0800200c9a66> ;"
            + "oa:hasSource <http://www.example.org/mypage.html> . "
            + "<http://example.org/user1> a foaf:Person ; "
            + "foaf:name \"Joe Bloggs\" . "
            + "<http://www.youtube.com/watch?v=uPh81LIe7B8> a dctypes:MovingImage ."
            + "<http://www.example.org/mypage.html> a dctypes:Text ."
            + "<urn:uuid:7645af80-975c-11e2-9e96-0800200c9a66> a oa:HTTPRequestState ; "
            + "rdf:value \"foo\" ; "
            + "rdf:value \"bar\" . "
            + "}";
    public static final String OA_INVALID_SR = "@prefix oa: <http://www.w3.org/ns/oa#> . " 
            + "@prefix foaf: <http://xmlns.com/foaf/0.1/> . "
            + "@prefix dctypes: <http://purl.org/dc/dcmitype/> . "
            + "@prefix dcterms: <http://purl.org/dc/terms/> . "
            + "<http://localhost:8080/lorestore/oa/sopabasic> { "
            + "<http://localhost:8080/lorestore/oa/sopabasic> a oa:Annotation ; "
            + "oa:annotatedBy <http://example.org/user1> ; "
            + "oa:annotatedAt \"2012-02-12T15:02:14Z\" ; "
            + "oa:motivatedBy oa:commenting ; "
            + "oa:hasTarget <89ef7820-9687-11e2-9e96-0800200c9a66> ;"
            + "oa:hasBody <http://www.youtube.com/watch?v=uPh81LIe7B8> . "
            + "<urn:uuid:0bf18730-96a3-11e2-9e96-0800200c9a66> a oa:FragmentSelector ; "
            + "dcterms:conformsTo <http://tools.ietf.org/rfc/rfc3236> ; "
            + "rdf:value \"#foo\" . "
            + "<89ef7820-9687-11e2-9e96-0800200c9a66> a oa:SpecificResource ; "
            + "oa:hasSelector <urn:uuid:0bf18730-96a3-11e2-9e96-0800200c9a66> ; "
            + "oa:hasSource <http://www.example.org/mypage2.html> ; "
            + "oa:hasSource <http://www.example.org/mypage.html> . "
            + "<http://example.org/user1> a foaf:Person ; "
            + "foaf:name \"Joe Bloggs\" . "
            + "<http://www.youtube.com/watch?v=uPh81LIe7B8> a dctypes:MovingImage ."
            + "<http://www.example.org/mypage.html> a dctypes:Text ."
            + "}";
    public static final String OA_SR_NO_CLASS = "@prefix oa: <http://www.w3.org/ns/oa#> . " 
            + "@prefix foaf: <http://xmlns.com/foaf/0.1/> . "
            + "@prefix dctypes: <http://purl.org/dc/dcmitype/> . "
            + "@prefix dcterms: <http://purl.org/dc/terms/> . "
            + "<http://localhost:8080/lorestore/oa/sopabasic> { "
            + "<http://localhost:8080/lorestore/oa/sopabasic> a oa:Annotation ; "
            + "oa:annotatedBy <http://example.org/user1> ; "
            + "oa:annotatedAt \"2012-02-12T15:02:14Z\" ; "
            + "oa:motivatedBy oa:commenting ; "
            + "oa:hasTarget <urn:uuid:89ef7820-9687-11e2-9e96-0800200c9a66> ;"
            + "oa:hasBody <http://www.youtube.com/watch?v=uPh81LIe7B8> . "
            + "<urn:uuid:0bf18730-96a3-11e2-9e96-0800200c9a66> a oa:FragmentSelector ; "
            + "dcterms:conformsTo <http://tools.ietf.org/rfc/rfc3236> ; "
            + "rdf:value \"#foo\" . "
            + "<urn:uuid:89ef7820-9687-11e2-9e96-0800200c9a66>  oa:hasSelector <urn:uuid:0bf18730-96a3-11e2-9e96-0800200c9a66> ; "
            + "oa:hasSource <http://www.example.org/mypage.html> . "
            + "<http://example.org/user1> a foaf:Person ; "
            + "foaf:name \"Joe Bloggs\" . "
            + "<http://www.youtube.com/watch?v=uPh81LIe7B8> a dctypes:MovingImage ."
            + "<http://www.example.org/mypage.html> a dctypes:Text ."
            + "}";
    public static final String OA_SPECIFIC_RESOURCE_NO_SOURCE_OR_SELECTOR = "@prefix oa: <http://www.w3.org/ns/oa#> . " 
            + "@prefix foaf: <http://xmlns.com/foaf/0.1/> . "
            + "@prefix dctypes: <http://purl.org/dc/dcmitype/> . "
            + "@prefix dcterms: <http://purl.org/dc/terms/> . "
            + "<http://localhost:8080/lorestore/oa/sopabasic> { "
            + "<http://localhost:8080/lorestore/oa/sopabasic> a oa:Annotation ; "
            + "oa:annotatedBy <http://example.org/user1> ; "
            + "oa:annotatedAt \"2012-02-12T15:02:14Z\" ; "
            + "oa:motivatedBy oa:commenting ; "
            + "oa:hasTarget <urn:uuid:89ef7820-9687-11e2-9e96-0800200c9a66> ;"
            + "oa:hasBody <http://www.youtube.com/watch?v=uPh81LIe7B8> . "
            + "<urn:uuid:89ef7820-9687-11e2-9e96-0800200c9a66> a oa:SpecificResource . "
            + "<http://example.org/user1> a foaf:Person ; "
            + "foaf:name \"Joe Bloggs\" . "
            + "<http://www.youtube.com/watch?v=uPh81LIe7B8> a dctypes:MovingImage ."
            + "<http://www.example.org/mypage.html> a dctypes:Text ."
            + "}";
    public static final String OA_FRAGMENT_SELECTOR_INVALID = "@prefix oa: <http://www.w3.org/ns/oa#> . " 
            + "@prefix foaf: <http://xmlns.com/foaf/0.1/> . "
            + "@prefix dctypes: <http://purl.org/dc/dcmitype/> . "
            + "@prefix dcterms: <http://purl.org/dc/terms/> . "
            + "<http://localhost:8080/lorestore/oa/sopabasic> { "
            + "<http://localhost:8080/lorestore/oa/sopabasic> a oa:Annotation ; "
            + "oa:annotatedBy <http://example.org/user1> ; "
            + "oa:annotatedAt \"2012-02-12T15:02:14Z\" ; "
            + "oa:motivatedBy oa:commenting ; "
            + "oa:hasTarget <urn:uuid:89ef7820-9687-11e2-9e96-0800200c9a66> ;"
            + "oa:hasBody <http://www.youtube.com/watch?v=uPh81LIe7B8> . "
            + "<urn:uuid:0bf18730-96a3-11e2-9e96-0800200c9a66> a oa:FragmentSelector . "
            + "<urn:uuid:89ef7820-9687-11e2-9e96-0800200c9a66> a oa:SpecificResource ; "
            + "oa:hasSelector <urn:uuid:0bf18730-96a3-11e2-9e96-0800200c9a66> ; "
            + "oa:hasSelector <urn:uuid:1f2269b0-96a7-11e2-9e96-0800200c9a66> ; "
            + "oa:hasSource <http://www.example.org/mypage.html> . "
            + "<http://example.org/user1> a foaf:Person ; "
            + "foaf:name \"Joe Bloggs\" . "
            + "<http://www.youtube.com/watch?v=uPh81LIe7B8> a dctypes:MovingImage ."
            + "<http://www.example.org/mypage.html> a dctypes:Text ."
            + "}";
    public static final String OA_SEMANTICTAG = "@prefix oa: <http://www.w3.org/ns/oa#> . " 
            + "@prefix foaf: <http://xmlns.com/foaf/0.1/> . "
            + "@prefix dctypes: <http://purl.org/dc/dcmitype/> . "
            + "<http://localhost:8080/lorestore/oa/sopabasic> { "
            + "<http://localhost:8080/lorestore/oa/sopabasic> a oa:Annotation ; "
            + "oa:annotatedBy <http://example.org/user1> ; "
            + "oa:annotatedAt \"2012-02-12T15:02:14Z\" ; "
            + "oa:motivatedBy oa:tagging ; "
            + "oa:hasBody <http://www.example.org/MyTag> ; "
            + "oa:hasTarget <http://en.wikipedia.org/> ."
            + "<http://example.org/user1> a foaf:Person ; "
            + "foaf:name \"Joe Bloggs\" . "
            + "<http://www.example.org/MyTag> a oa:SemanticTag ."
            + "<http://en.wikipedia.org/> a dctypes:Text . "
            + "}";
    public static final String OA_SEMANTICTAG_WRONG_MOTIVATION = "@prefix oa: <http://www.w3.org/ns/oa#> . " 
            + "@prefix foaf: <http://xmlns.com/foaf/0.1/> . "
            + "@prefix dctypes: <http://purl.org/dc/dcmitype/> . "
            + "<http://localhost:8080/lorestore/oa/sopabasic> { "
            + "<http://localhost:8080/lorestore/oa/sopabasic> a oa:Annotation ; "
            + "oa:annotatedBy <http://example.org/user1> ; "
            + "oa:annotatedAt \"2012-02-12T15:02:14Z\" ; "
            + "oa:motivatedBy oa:commenting ; "
            + "oa:hasBody <http://www.example.org/MyTag> ; "
            + "oa:hasTarget <http://en.wikipedia.org/> ."
            + "<http://example.org/user1> a foaf:Person ; "
            + "foaf:name \"Joe Bloggs\" . "
            + "<http://www.example.org/MyTag> a oa:SemanticTag ."
            + "<http://en.wikipedia.org/> a dctypes:Text . "
            + "}";
    public static final String OA_TAGGING_MOTIVATION_NOT_TAG = "@prefix oa: <http://www.w3.org/ns/oa#> . " 
            + "@prefix foaf: <http://xmlns.com/foaf/0.1/> . "
            + "@prefix dctypes: <http://purl.org/dc/dcmitype/> . "
            + "<http://localhost:8080/lorestore/oa/sopabasic> { "
            + "<http://localhost:8080/lorestore/oa/sopabasic> a oa:Annotation ; "
            + "oa:annotatedBy <http://example.org/user1> ; "
            + "oa:annotatedAt \"2012-02-12T15:02:14Z\" ; "
            + "oa:motivatedBy oa:tagging ; "
            + "oa:hasBody <http://www.youtube.com/watch?v=uPh81LIe7B8> ; "
            + "oa:hasTarget <http://en.wikipedia.org/> ."
            + "<http://example.org/user1> a foaf:Person ; "
            + "foaf:name \"Joe Bloggs\" . "
            + "<http://www.youtube.com/watch?v=uPh81LIe7B8> a dctypes:MovingImage ."
            + "<http://en.wikipedia.org/> a dctypes:Text . "
            + "}";
    public static final String OA_CONTENT_TYPES_WARNING = "@prefix oa: <http://www.w3.org/ns/oa#> . " 
            + "@prefix foaf: <http://xmlns.com/foaf/0.1/> . "
            + "@prefix dctypes: <http://purl.org/dc/dcmitype/> . "
            + "<http://localhost:8080/lorestore/oa/sopabasic> { "
            + "<http://localhost:8080/lorestore/oa/sopabasic> a oa:Annotation ; "
            + "oa:annotatedBy <http://example.org/user1> ; "
            + "oa:annotatedAt \"2012-02-12T15:02:14Z\" ; "
            + "oa:motivatedBy oa:commenting ; "
            + "oa:hasBody <http://www.youtube.com/watch?v=uPh81LIe7B8> ; "
            + "oa:hasTarget <http://en.wikipedia.org/> ."
            + "<http://example.org/user1> a foaf:Person ; "
            + "foaf:name \"Joe Bloggs\" . "
            + "<http://en.wikipedia.org/> a dctypes:Text . "
            + "}";
    public static final String OA_CONTENT_TYPES_NOT_DC = "@prefix oa: <http://www.w3.org/ns/oa#> . " 
            + "@prefix foaf: <http://xmlns.com/foaf/0.1/> . "
            + "@prefix dctypes: <http://purl.org/dc/dcmitype/> . "
            + "@prefix ex: <http://example.org/> ."
            + "<http://localhost:8080/lorestore/oa/sopabasic> { "
            + "<http://localhost:8080/lorestore/oa/sopabasic> a oa:Annotation ; "
            + "oa:annotatedBy <http://example.org/user1> ; "
            + "oa:annotatedAt \"2012-02-12T15:02:14Z\" ; "
            + "oa:motivatedBy oa:commenting ; "
            + "oa:hasBody <http://www.youtube.com/watch?v=uPh81LIe7B8> ; "
            + "oa:hasTarget <http://en.wikipedia.org/> ."
            + "<http://example.org/user1> a foaf:Person ; "
            + "foaf:name \"Joe Bloggs\" . "
            + "<http://www.youtube.com/watch?v=uPh81LIe7B8> a dctypes:MovingImage ."
            + "<http://en.wikipedia.org/> a ex:Foo . "
            + "}";
    public static final String OA_MOTIVATION_NO_INSTANCE  = "@prefix oa: <http://www.w3.org/ns/oa#> . " 
            + "@prefix foaf: <http://xmlns.com/foaf/0.1/> . "
            + "@prefix dctypes: <http://purl.org/dc/dcmitype/> . "
            + "@prefix ex: <http://example.org/> . "
            + "@prefix skos: <http://www.w3.org/2004/02/skos/core#> . "
            + "<http://localhost:8080/lorestore/oa/sopabasic> { "
            + "<http://localhost:8080/lorestore/oa/sopabasic> a oa:Annotation ; "
            + "oa:annotatedBy <http://example.org/user1> ; "
            + "oa:annotatedAt \"2012-02-12T15:02:14Z\" ; "
            + "oa:motivatedBy ex:specialisedMotivation ; "
            + "oa:hasBody <http://www.youtube.com/watch?v=uPh81LIe7B8> ; "
            + "oa:hasTarget <http://en.wikipedia.org/> ."
            + "<http://example.org/user1> a foaf:Person ; "
            + "foaf:name \"Joe Bloggs\" . "
            + "<http://www.youtube.com/watch?v=uPh81LIe7B8> a dctypes:MovingImage ."
            + "<http://en.wikipedia.org/> a dctypes:Text . "
            + "}";
    public static final String OA_MOTIVATION_NO_BROADER  = "@prefix oa: <http://www.w3.org/ns/oa#> . " 
            + "@prefix foaf: <http://xmlns.com/foaf/0.1/> . "
            + "@prefix dctypes: <http://purl.org/dc/dcmitype/> . "
            + "@prefix ex: <http://example.org/> . "
            + "@prefix skos: <http://www.w3.org/2004/02/skos/core#> . "
            + "<http://localhost:8080/lorestore/oa/sopabasic> { "
            + "<http://localhost:8080/lorestore/oa/sopabasic> a oa:Annotation ; "
            + "oa:annotatedBy <http://example.org/user1> ; "
            + "oa:annotatedAt \"2012-02-12T15:02:14Z\" ; "
            + "oa:motivatedBy ex:specialisedMotivation ; "
            + "oa:hasBody <http://www.youtube.com/watch?v=uPh81LIe7B8> ; "
            + "oa:hasTarget <http://en.wikipedia.org/> ."
            + "<http://example.org/user1> a foaf:Person ; "
            + "foaf:name \"Joe Bloggs\" . "
            + "<http://www.youtube.com/watch?v=uPh81LIe7B8> a dctypes:MovingImage ."
            + "<http://en.wikipedia.org/> a dctypes:Text . "
            + "ex:specialisedMotivation a oa:Motivation . "
            + "}";
    public static final String OA_MOTIVATION_VALID  = "@prefix oa: <http://www.w3.org/ns/oa#> . " 
            + "@prefix foaf: <http://xmlns.com/foaf/0.1/> . "
            + "@prefix dctypes: <http://purl.org/dc/dcmitype/> . "
            + "@prefix ex: <http://example.org/> . "
            + "@prefix skos: <http://www.w3.org/2004/02/skos/core#> . "
            + "<http://localhost:8080/lorestore/oa/sopabasic> { "
            + "<http://localhost:8080/lorestore/oa/sopabasic> a oa:Annotation ; "
            + "oa:annotatedBy <http://example.org/user1> ; "
            + "oa:annotatedAt \"2012-02-12T15:02:14Z\" ; "
            + "oa:motivatedBy ex:specialisedMotivation ; "
            + "oa:hasBody <http://www.youtube.com/watch?v=uPh81LIe7B8> ; "
            + "oa:hasTarget <http://en.wikipedia.org/> ."
            + "<http://example.org/user1> a foaf:Person ; "
            + "foaf:name \"Joe Bloggs\" . "
            + "<http://www.youtube.com/watch?v=uPh81LIe7B8> a dctypes:MovingImage ."
            + "<http://en.wikipedia.org/> a dctypes:Text . "
            + "ex:specialisedMotivation a oa:Motivation ; "
            + " skos:broader oa:commenting ."
            + "}";
    public static final String OA_BASIC_STYLED_BY = "@prefix oa: <http://www.w3.org/ns/oa#> ."
            + "<http://localhost:8080/lorestore/oa/sopabasic> {"
            + "<http://localhost:8080/lorestore/oa/sopabasic> a oa:Annotation ; "
            + "oa:hasBody <http://www.youtube.com/watch?v=uPh81LIe7B8> ; " 
            + "oa:styledBy <http://www.example.org/MyStyle> ;"
            + "oa:hasTarget <http://en.wikipedia.org/> .}";
    public static final String OA_BASIC_MULTIPLE_STYLED_BY = "@prefix oa: <http://www.w3.org/ns/oa#> ."
            + "<http://localhost:8080/lorestore/oa/sopabasic> {"
            + "<http://localhost:8080/lorestore/oa/sopabasic> a oa:Annotation ; "
            + "oa:hasBody <http://www.youtube.com/watch?v=uPh81LIe7B8> ; " 
            + "oa:styledBy <http://www.example.org/MyStyle> ;"
            + "oa:styledBy <http://www.example.org/MyStyle2> ;"
            + "oa:hasTarget <http://en.wikipedia.org/> .}";
    
}
